name: CI avec Node.js
run-name: ${{ github.actor }} est entrain d'apprendre GitHub Actions
on: [push]
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - run: node -v
      - run: npm install
      - run: npm test
